version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'cognito-starter'
    ports:
      - "5432:5432"
    volumes:
      - ./init-user.sql:/docker-entrypoint-initdb.d/init-user.sql
